### ISSUE TITLE
STORY02a:As a BVI Monarch user, I want to be able to verbally ask a question about the overall experience or a about a specific area I'm touching in the experience I've already received, so that I can get a spoken response.

### ISSUE THREAD

**Issue by VenissaCarolQuadros** [Shared-Reality-Lab/IMAGE-Monarch#50]
**Tasks:**
- [x] Design and implement user interface that will allow a Monarch user to make a verbal follow up query and optionally capture the area of focus indicated by the Monarch user if desired
- [x] Implement Speech recognition to convert verbal queries to text
- [x] Implement features to generate follow up requests to server
~~- [ ] Implement a dummy handler to return a placeholder response for a follow up query (Unsure if there need to be some changes to server before I can do this)~~

**DEMO:** A Monarch user will be able to verbally ask a question and optionally indicate a region of interest about the experience they have received. The Monarch application generates a follow-up request and (If the last task is completed) reads out the response.

**Comment by VenissaCarolQuadros** [comment]
Removed the last work item as changes to the server that will allow this are yet to implemented. To be done in a later sprint. 

Currently, the client application generates requests with the query, focus and previous fields. There is some work that needs to be done on the client application to handle the 'follow up' responses from the server but it will be convenient to do this once the last work item is completed as it could also be tested.
